### PR TITLE
First version of the provision script

### PR DESCRIPTION
**Pull request by vernig**
Add a script to provision the Flex account 

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by vernig** [comment]
@bermudezmt @ktalebian I finally found some time to work on the provision script. After switching to this branch, run `npm install` because I added some dependencies. 

To execute the provisioning, run: 
```
node provision
```

and follow the instructions. I tested on my Flex project and works fine, but it definitely need more tests. It's safe to execute on a Flex project already provisioned (the script detects if resources have been created already). Currently the Studio Flow is re-created, but I'm working in updating it instead. 

Have a try when you can and let me know what you think 

p.s. At the moment the script is all self contained. I'm thinking to split it in more files, but since it's usually used only once, IMHO that shouldn't be a priority. But I'm keen to get your view on that.

**Comment by vernig** [comment]
@bermudezmt @ktalebian I really had to scratch that itch. I update the PR with: 
* Move the provision script(s) in its own folder and distribute the implementation over multiple files (_helpers_) 
* Studio flow is updated if another one with name `CallbackVoiceMailFlow` already exists

Let me know what you think

**Comment by dfokina** [comment]
Hi @vernig! Thank you so much for your pull request. @bermudezmt and I tested it – everything works except for when the account doesn't have a phone number: 
```
(node:1165) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at ListPrompt.getCurrentValue (/Users/dfokina/Documents/GitHub/DevEd/plugin-queued-callbacks-and-voicemail/node_modules/inquirer/lib/prompts/list.js:148:53)
    at MapSubscriber._next (/Users/dfokina/Documents/GitHub/DevEd/plugin-queued-callbacks-and-voicemail/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/Users/dfokina/Documents/GitHub/DevEd/plugin-queued-callbacks-and-voicemail/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeSubscriber._next (/Users/dfokina/Documents/GitHub/DevEd/plugin-queued-callbacks-and-voicemail/node_modules/rxjs/internal/operators/take.js:54:30)
    at TakeSubscriber.Subscriber.next (/Users/dfokina/Documents/GitHub/DevEd/plugin-queued-callbacks-and-voicemail/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Interface.handler (/Users/dfokina/Documents/GitHub/DevEd/plugin-queued-callbacks-and-voicemail/node_modules/rxjs/internal/observable/fromEvent.js:22:28)
    at Interface.emit (events.js:412:35)
    at Interface._onLine (readline.js:364:10)
    at Interface._line (readline.js:700:8)
    at Interface._ttyWrite (readline.js:1045:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1165) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1165) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

One other thing we noticed after we sorted out the phone number purchasing issue was the same command output:
```
✔ Task Channels created
✔ "CallbackandVoicemailQueue" Task Queue created
✔ "Assign To Anyone" workflow updated
✔ Serverless deployed to plugin-queued-callbacks-voicemail-functions-4248-dev.twil.io
✔ Studio Flow created
```
The script isn't actually recreating the same resources, right? Everything around deployment worked smoothly, we just wanted to call out the potential source of confusion as far as provisioning of resources goes. Let us know if you have follow-up questions!

**Comment by vernig** [comment]
Hey @dfokina @bermudezmt thanks for taking the time to test the PR and your input. 

Good point around the phone number. I'll add a check for phone numbers (and other requisite) at the beginning of the script and add a commit to this PR. 

> The script isn't actually recreating the same resources, right?

Correct. The script is checking if the resource (task channel, task queue, workflow, etc) exists already, and if it does, it only updates it. So it's safe to run the script any number of times. I can change the printout message (e.g. `Task Channels updated` in case the resource is updated), but that may complicate the structure of the script. Let me think about it.

**Comment by vernig** [comment]
Hey @dfokina @bermudezmt sorry that it took me so long. I've made the changes and improve the error handling / logging. Have a try now and let me know what you think.

**Comment by dfokina** [comment]
Hi @vernig, we tested it just now and we're running into an issue with the plugin UI enhancement not rendering in Task Info Panel in Flex. We do not see the regular buttons that we expect nor do we get a voicemail recording or transcript. We will need to follow up whether this is caused by the following warning:

`The React version 16.5.2 installed locally is incompatible with the React version 17.0.2 installed on your Flex project.
`

We will circle back to this next week.

**Comment by dfokina** [comment]
Hi, we tested the script with Flex 1.27.0 and everything works great. It was able to redeploy the functions and assets to the same domain we already had.
We just realised that the plugin deployment prompt is missing the "major/minor" version flag:

```
You can now deploy the plugin using:
 $ twilio flex:plugins:deploy --changelog="First version"
```

It doesn't error out, but it defaults to "minor" release. It would good to point out that they can also deploy a major version.

**Review by bermudezmt — APPROVED** [review]
LGTM. Thank you so much! We will have to note that the `twilio flex:plugins:deploy` command does not automatically pick up the account SID that you use for the provisioning of resources. Customers may have to additionally activate that account as their currently selected Twilio profile.

**Pull request merged**
